"""Domain configuration: keyword sets, section lists, thresholds, and defaults."""

from __future__ import annotations

FINANCE_KEYWORDS = {
    "acao",
    "acoes",
    "agronegocio",
    "b3",
    "balanco",
    "banco central",
    "bolsa",
    "cambio",
    "copom",
    "credito",
    "criptomoeda",
    "debenture",
    "dividendo",
    "dolar",
    "economia",
    "empresa",
    "etf",
    "fii",
    "fundo",
    "ibovespa",
    "ifix",
    "inflacao",
    "investimento",
    "investimentos",
    "investidor",
    "investidores",
    "investir",
    "ipo",
    "juros",
    "lucro",
    "mercado",
    "petrobras",
    "real",
    "renda fixa",
    "risco",
    "selic",
    "tesouro",
    "vale",
}

STRONG_FINANCE_KEYWORDS = {
    "acao",
    "acoes",
    "aluguel",
    "ativo",
    "ativos",
    "b3",
    "bolsa",
    "cambio",
    "cdi",
    "copom",
    "credito",
    "debenture",
    "dividendo",
    "dolar",
    "emprestimo",
    "etf",
    "fii",
    "financiamento",
    "free float",
    "fundo",
    "ibovespa",
    "ifix",
    "inflacao",
    "investidor",
    "investidores",
    "investimento",
    "investimentos",
    "ipo",
    "juros",
    "lucro",
    "renda fixa",
    "risco",
    "selic",
    "taxa",
    "tesouro",
    "valuation",
}

AMBIGUOUS_STRONG_FINANCE_KEYWORDS = {
    "acao",
    "ativo",
    "ativos",
    "taxa",
}

BRAZIL_MARKET_KEYWORDS = {
    "b3",
    "anbima",
    "banco central do brasil",
    "banco central brasileiro",
    "bcb",
    "bndes",
    "bovespa",
    "brasil",
    "brasileira",
    "brasileiras",
    "brasileiro",
    "brasileiros",
    "copom",
    "cvm",
    "dolar",
    "dolar futuro",
    "ibovespa",
    "ifix",
    "ibc-br",
    "ipca",
    "mercado brasileiro",
    "ministerio da fazenda",
    "real brasileiro",
    "selic",
    "tesouro direto",
}

FOREIGN_CONTEXT_KEYWORDS = {
    "argentina",
    "argentino",
    "argentinos",
    "asia-pacifico",
    "bank of england",
    "bce",
    "boe",
    "buenos aires",
    "cepo",
    "china",
    "dow jones",
    "ecb",
    "eua",
    "europa",
    "fed",
    "federal reserve",
    "fomc",
    "fmi",
    "japao",
    "japones",
    "japonesa",
    "milei",
    "nasdaq",
    "nikkei",
    "powell",
    "s&p 500",
    "treasury",
    "wall street",
    "yuan",
    "zona do euro",
}

DIRECT_BRAZIL_CONTEXT_KEYWORDS = {
    "ante o real",
    "banco do brasil",
    "banco central do brasil",
    "banco central brasileiro",
    "b3",
    "bb seguridade",
    "bcb",
    "bndes",
    "bovespa",
    "contra o real",
    "copom",
    "cvm",
    "dis",
    "economia brasileira",
    "frente ao real",
    "ibc-br",
    "ibovespa",
    "ifix",
    "ipca",
    "credito imobiliario",
    "itau",
    "itau unibanco",
    "juros futuros",
    "mercado brasileiro",
    "ministerio da fazenda",
    "pib brasileiro",
    "petrobras",
    "real brasileiro",
    "selic",
    "tesouro nacional",
    "tesouro direto",
    "vale",
}

CORPORATE_RESULTS_METRIC_MARKERS = {
    "balanco",
    "ebitda",
    "guidance",
    "lucro",
    "prejuizo",
}

CORPORATE_RESULTS_PERIOD_MARKERS = {
    "1 tri",
    "1o tri",
    "1t",
    "2 tri",
    "2o tri",
    "2t",
    "3 tri",
    "3o tri",
    "3t",
    "4 tri",
    "4o tri",
    "4t",
    "ano",
    "anual",
    "primeiro trimestre",
    "quarto trimestre",
    "segundo trimestre",
    "semestre",
    "semestral",
    "terceiro trimestre",
    "trimestre",
    "trimestral",
}

AGGREGATE_RESULTS_MARKERS = {
    "bancos",
    "companhias",
    "empresas",
    "industria",
    "industrias",
    "setor",
    "setores",
}

FOCUSED_TOPIC_KEYWORDS = {
    "aluguel",
    "b3",
    "banco central",
    "banco central do brasil",
    "bcb",
    "boletim focus",
    "cambio",
    "cdi",
    "copom",
    "credito",
    "curva de juros",
    "debenture",
    "debentures",
    "dividendo",
    "dividendos",
    "dolar",
    "emprestimo",
    "financiamento",
    "focus",
    "ibovespa",
    "indice futuro",
    "inflacao",
    "ipca",
    "juros",
    "mini-indice",
    "minicontratos",
    "pib",
    "pmi",
    "pmis",
    "provento",
    "proventos",
    "renda fixa",
    "selic",
    "spread",
    "swap cambial",
    "tesouro",
    "tesouro direto",
}

DIRECTIONAL_SIGNAL_KEYWORDS = {
    "acelera",
    "aceleracao",
    "alta",
    "amplia",
    "aperta",
    "aperto",
    "aposta",
    "aprova",
    "arrefece",
    "avanca",
    "avanco",
    "cai",
    "caem",
    "caiu",
    "contrai",
    "corte",
    "cortes",
    "desacelera",
    "desaceleracao",
    "desvaloriza",
    "despenca",
    "dispara",
    "eleva",
    "otimismo",
    "pessimismo",
    "pressao",
    "projecao",
    "projecoes",
    "queda",
    "recorde",
    "recua",
    "recuo",
    "reduz",
    "reducao",
    "revisa",
    "revisao",
    "rompe",
    "salta",
    "sobe",
    "sobem",
    "subiu",
    "suspende",
    "surpreende",
    "surpresa",
    "valoriza",
    "veto",
}

SOURCE_PRIORITY: dict[str, int] = {
    "Valor Econômico": 0,
    "InfoMoney": 1,
    "Exame": 2,
}

GROSS_SECTION_ALLOWLIST: dict[str, set[str]] = {
    "InfoMoney": {
        "mercados",
        "onde-investir",
        "economia",
        "negocios",
        "fundos",
        "cotacoes",
        "colunistas",
    },
    "Exame": {
        "invest",
        "economia",
        "mercado",
        "negocios",
    },
    "Valor Econômico": {
        "financas",
        "empresas",
        "politica",
        "brasil",
        "mundo",
        "agronegocios",
        "legislacao",
    },
}

GROSS_SECTION_DENYLIST: dict[str, set[str]] = {
    "InfoMoney": {
        "consumo",
        "esportes",
        "entretenimento",
        "tecnologia",
        "turismo",
        "variedades",
    },
    "Exame": {
        "casual",
        "carreira",
        "esg",
        "pop",
        "science-health",
    },
    "Valor Econômico": {
        "eu-e",
        "carreira",
        "cultura",
        "gastronomia",
    },
}

STRICT_SECTION_SIGNAL_THRESHOLD: dict[str, int] = {
    "brasil": 6,
    "legislacao": 5,
    "mundo": 5,
    "politica": 6,
}

HIGH_SCRUTINY_SECTIONS: set[str] = {
    "agronegocios",
    "brasil",
    "colunistas",
    "empresas",
    "legislacao",
    "mundo",
    "negocios",
    "politica",
}

ADVISORY_SECTIONS: set[str] = {
    "advisor",
    "invest",
    "onde-investir",
}

EDITORIAL_SECTIONS: set[str] = {
    "advisor",
    "colunistas",
    "invest",
    "negocios",
    "onde-investir",
}

EDITORIAL_TITLE_MARKERS: set[str] = {
    "a fintech de",
    "destaques da semana",
    "aposta do ano",
    "entenda a data",
    "motores de retorno",
    "na carteira do",
    "o ceo que",
    "os destaques da semana",
    "qual o saldo",
    "veja detalhes",
    "vira aposta",
}

EDITORIAL_LEAD_MARKERS: set[str] = {
    "gestor da casa",
    "portifolio da xp asset",
    "portfolio da xp asset",
    "responsaveis pelo desempenho dos fundos",
    "xp asset",
}

CORPORATE_ANNOUNCEMENT_TITLE_MARKERS: set[str] = {
    # Dividend / JCP payment announcements
    "anuncia dividendo",
    "aprova dividendo",
    "aprova jcp",
    "data ex-dividendo",
    "data ex dividendo",
    "declara jcp",
    "distribui dividendo",
    "distribuicao de dividendo",
    "dividend yield de",
    "dividendo por acao",
    "dividendos por acao",
    "jcp de r$",
    "pagamento de dividendo",
    "pagamento de dividendos",
    "retorno com dividendos de",
    # Results / earnings disclosures
    "apresenta resultado",
    "divulga balanco",
    "divulga resultado",
    "lucro liquido de",
    "registra lucro",
    "registra prejuizo",
    "reporta resultado",
    "reverte prejuizo",
    "reverte resultado",
    "lucra no",
    "lucra em",
    "lucra r$",
    "prejuizo no",
    "prejuizo em",
    "prejuizo r$",
    "resultado liquido",
    "resultado operacional",
    "balanco trimestral",
    "resultado trimestral",
    "resultado do trimestre",
    "lucro do trimestre",
    "prejuizo do trimestre",
    "receita do trimestre",
    "receita trimestral",
    "contas do trimestre",
    "apos o balanco",
    "apos balanco",
    # Capital raising / operational updates
    "anuncio de oferta de acoes",
    "anuncio de oferta primaria de acoes",
    "dados operacionais",
    "numeros operacionais",
    "oferta de acoes",
    "oferta primaria de acoes",
    "oferta subsequente de acoes",
    "volume medio negociado",
    "volume negociado em",
    # Debenture / bond issuances
    "coloca debenture",
    "emissao de debenture",
    "emite debenture",
    "oferta de debenture",
}

FINAL_SECTION_DENYLIST: set[str] = {
    "esg",
}

BOILERPLATE_SNIPPETS: set[str] = {
    "publicidade",
    "acompanhe os mercados com nossas ferramentas",
    "conheca o valor one",
    "conheça o valor one",
    "continua depois da publicidade",
    "leia mais",
    "saiba mais",
    "veja tambem",
    "veja também",
    "receba as noticias",
    "receba as notícias",
    "assine agora",
}

SPONSORED_AUTHOR_MARKERS: set[str] = {
    "exame solutions",
}

SPONSORED_TEXT_MARKERS: set[str] = {
    "parceiro institucional",
}

GENERIC_TITLE_DENYLIST: set[str] = {
    "ao vivo",
    "cobertura ao vivo",
    "destaques",
    "minuto a minuto",
    "ultimas noticias",
    "ultimas notícias",
}

ROUNDUP_URL_MARKERS: set[str] = {
    "ao-vivo",
    "cobertura-ao-vivo",
    "destaques",
    "minuto-a-minuto",
    "ultimas-noticias",
}

OUTPUT_FIELDS: tuple[str, ...] = (
    "source",
    "url",
    "section",
    "authors",
    "tags",
    "title",
    "description",
    "lead",
    "sentiment_text",
    "published_at",
    "week_key",
    "week_start",
    "week_end",
    "weekday",
)

DEFAULT_REQUEST_DELAY: float = 0.2
DEFAULT_ATTEMPT_MULTIPLIER: int = 6
DEFAULT_RANDOM_SEED: int = 42
DEFAULT_ENRICH_WORKERS: int = 8
DEFAULT_SITEMAP_WORKERS: int = 16
